# Speed Dating Project
## Univariate Data Analysis

In [1]:
# libraries
import os
import sys
import inspect
sys.path.append("../src")

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

from analysis import analysis
from shared import directories
from shared import filenames
from shared import variables
from visualization import visual

### Obtain training data

In [2]:
train = pd.read_csv(os.path.join(directories.INTERIM_DATA_DIR,
                              filenames.TRAIN_FILENAME),
                 encoding="Latin-1", low_memory=False)

### Inspect Data Structure

In [3]:
print(train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5361 entries, 0 to 5360
Columns: 121 entries, has_null to match
dtypes: float64(57), int64(6), object(58)
memory usage: 4.9+ MB
None

### Examine qualitative variables

In [6]:
train_qual = train.select_dtypes(include=[np.object])
train_qual_describe = analysis.describe_qual(train_qual)
train_qual_describe

                                count unique        top  freq  missing
gender                           5361      2       male  2698        0
d_d_age                          5361      4      [2-3]  1560        0
race                             5324      5  caucasian  3033       37
race_o                           5305      5  caucasian  3004       56
d_importance_same_race           5361      3      [2-5]  1979        0
d_importance_same_religion       5361      3      [0-1]  1985        0
d_pref_o_attractive              5361      3   [21-100]  1935        0
d_pref_o_sincere                 5361      3    [16-20]  2426        0
d_pref_o_intelligence            5361      3    [16-20]  2707        0
d_pref_o_funny                   5361      3    [16-20]  2471        0
d_pref_o_ambitious               5361      3     [0-15]  4262        0
d_pref_o_shared_interests        5361      3     [0-15]  3876        0
d_attractive_o                   5361      3      [6-8]  2903        0
d_sincere_o                      5361      3      [6-8]  3311        0
d_intelligence_o                 5361      3      [6-8]  3432        0
d_funny_o                        5361      3      [6-8]  2980        0
d_ambitous_o                     5361      3      [6-8]  2971        0
d_shared_interests_o             5361      3      [0-5]  2999        0
d_attractive_important           5361      3   [21-100]  1928        0
d_sincere_important              5361      3    [16-20]  2458        0
d_intelligence_important         5361      3    [16-20]  2732        0
d_funny_important                5361      3    [16-20]  2523        0
d_ambition_important             5361      3     [0-15]  4280        0
d_shared_interests_important     5361      3     [0-15]  3901        0
d_attractive                     5361      3      [6-8]  3987        0
d_sincere                        5361      3     [9-10]  2612        0
d_intelligence                   5361      3      [6-8]  3157        0
d_funny                          5361      3      [6-8]  2743        0
d_ambition                       5361      3      [6-8]  2809        0
d_attractive_partner             5361      3      [6-8]  2905        0
d_sincere_partner                5361      3      [6-8]  3335        0
d_intelligence_partner           5361      3      [6-8]  3516        0
d_funny_partner                  5361      3      [6-8]  2985        0
d_ambition_partner               5361      3      [6-8]  2983        0
d_shared_interests_partner       5361      3      [0-5]  3003        0
d_sports                         5361      3      [6-8]  2083        0
d_tvsports                       5361      3      [0-5]  3316        0
d_exercise                       5361      3      [6-8]  2312        0
d_dining                         5361      3      [6-8]  2629        0
d_museums                        5361      3      [6-8]  2734        0
d_art                            5361      3      [6-8]  2600        0
d_hiking                         5361      3      [0-5]  2377        0
d_gaming                         5361      3      [0-5]  3911        0
d_clubbing                       5361      3      [6-8]  2470        0
d_reading                        5361      3      [6-8]  2327        0
d_tv                             5361      3      [0-5]  2706        0
d_theater                        5361      3      [6-8]  2539        0
d_movies                         5361      3      [6-8]  2679        0
d_concerts                       5361      3      [6-8]  2718        0
d_music                          5361      3      [6-8]  2532        0
d_shopping                       5361      3      [0-5]  2559        0
d_yoga                           5361      3      [0-5]  3488        0
d_interests_correlate            5361      3   [0-0.33]  1950        0
d_expected_happy_with_sd_people  5361      3      [5-6]  2583        0
d_expected_num_interested_in_me  5361      3      [0-3]  4706        0
d_expected_num_matches           5361      3      [0-2]  2918        0
d_like                           5361      3      [6-8]  3093        0
d_guess_prob_liked               5361      3      [5-6]  2057        0

### Examine Quantitative Variables

In [5]:
train_quant = train.select_dtypes(include=[np.number])
train_quant_describe = analysis.describe_quant(train_quant)
with pd.option_context('display.max_rows', None, 'display.max_columns', None):    
    display(train_quant_describe)

,count,missing,min,25%,mean,50%,75%,max,skew,kurtosis
has_null,5361.0,0,0.00,1.00,0.877448,1.00,1.00,1.00,-2.302061,3.299486
age,5303.0,58,18.00,24.00,26.394682,26.00,28.00,55.00,NaN,NaN
age_o,5286.0,75,18.00,24.00,26.381952,26.00,28.00,55.00,NaN,NaN
d_age,5361.0,0,0.00,1.00,4.197724,3.00,5.00,37.00,3.198152,13.525411
samerace,5361.0,0,0.00,0.00,0.395449,0.00,1.00,1.00,0.427660,-1.817107
importance_same_race,5311.0,50,0.00,1.00,3.780644,3.00,6.00,10.00,NaN,NaN
importance_same_religion,5311.0,50,1.00,1.00,3.645076,3.00,6.00,10.00,NaN,NaN
pref_o_attractive,5297.0,64,0.00,15.00,22.541193,20.00,25.00,100.00,NaN,NaN
pref_o_sincere,5297.0,64,0.00,15.00,17.300470,18.37,20.00,60.00,NaN,NaN
pref_o_intelligence,5297.0,64,0.00,17.39,20.246825,20.00,23.81,50.00,NaN,NaN
pref_o_funny,5289.0,72,0.00,15.00,17.446366,18.00,20.00,50.00,NaN,NaN
pref_o_ambitious,5281.0,80,0.00,5.00,10.767216,10.00,15.00,53.00,NaN,NaN
pref_o_shared_interests,5268.0,93,0.00,9.09,11.900864,11.11,16.00,30.00,NaN,NaN
attractive_o,5210.0,151,0.00,5.00,6.201228,6.00,8.00,10.50,NaN,NaN
sincere_o,5163.0,198,0.00,6.00,7.172574,7.00,8.00,10.00,NaN,NaN
intelligence_o,5149.0,212,0.00,6.00,7.369781,7.00,8.00,10.00,NaN,NaN
funny_o,5116.0,245,0.00,5.00,6.415559,7.00,8.00,10.00,NaN,NaN
ambition_o,4898.0,463,0.00,6.00,6.769702,7.00,8.00,10.00,NaN,NaN
shared_interests_o,4661.0,700,0.00,4.00,5.487449,6.00,7.00,10.00,NaN,NaN
attractive_important,5311.0,50,0.00,15.00,22.546935,20.00,25.00,100.00,NaN,NaN
sincere_important,5311.0,50,0.00,15.00,17.335202,18.18,20.00,60.00,NaN,NaN
intelligence_important,5311.0,50,0.00,17.31,20.265238,20.00,23.81,50.00,NaN,NaN
funny_important,5307.0,54,0.00,15.00,17.542958,18.00,20.00,50.00,NaN,NaN
ambition_important,5300.0,61,0.00,5.00,10.673434,10.00,15.00,53.00,NaN,NaN
shared_interests_important,5287.0,74,0.00,8.33,11.787554,10.64,16.00,30.00,NaN,NaN
attractive,5292.0,69,2.00,6.00,7.091459,7.00,8.00,10.00,NaN,NaN
sincere,5292.0,69,2.00,8.00,8.290627,8.00,9.00,10.00,NaN,NaN
intelligence,5292.0,69,2.00,7.00,7.730537,8.00,9.00,10.00,NaN,NaN
funny,5292.0,69,3.00,8.00,8.395503,8.00,9.00,10.00,NaN,NaN
ambition,5292.0,69,2.00,7.00,7.572373,8.00,9.00,10.00,NaN,NaN
attractive_partner,5224.0,137,0.00,5.00,6.193128,6.00,8.00,10.00,NaN,NaN
sincere_partner,5180.0,181,0.00,6.00,7.184653,7.00,8.00,10.00,NaN,NaN
intelligence_partner,5168.0,193,0.00,6.00,7.367744,7.00,8.00,10.00,NaN,NaN
funny_partner,5128.0,233,0.00,5.00,6.405421,7.00,8.00,10.00,NaN,NaN
ambition_partner,4898.0,463,0.00,6.00,6.791548,7.00,8.00,10.00,NaN,NaN
shared_interests_partner,4670.0,691,0.00,4.00,5.475268,6.00,7.00,10.00,NaN,NaN
sports,5311.0,50,1.00,5.00,6.457729,7.00,9.00,10.00,NaN,NaN
tvsports,5311.0,50,1.00,2.00,4.594238,4.00,7.00,10.00,NaN,NaN
exercise,5311.0,50,1.00,5.00,6.244963,7.00,8.00,10.00,NaN,NaN
dining,5311.0,50,1.00,7.00,7.794577,8.00,9.00,10.00,NaN,NaN
museums,5311.0,50,0.00,6.00,7.008285,7.00,9.00,10.00,NaN,NaN
art,5311.0,50,0.00,5.00,6.734702,7.00,8.00,10.00,NaN,NaN
hiking,5311.0,50,0.00,4.00,5.762945,6.00,8.00,10.00,NaN,NaN
gaming,5311.0,50,0.00,1.00,3.851252,3.00,6.00,14.00,NaN,NaN
clubbing,5311.0,50,0.00,4.00,5.775937,6.00,8.00,10.00,NaN,NaN
reading,5311.0,50,1.00,7.00,7.695914,8.00,9.00,13.00,NaN,NaN
tv,5311.0,50,1.00,3.00,5.266240,5.00,7.00,10.00,NaN,NaN
theater,5311.0,50,0.00,5.00,6.782339,7.00,8.00,10.00,NaN,NaN
movies,5311.0,50,0.00,7.00,7.913576,8.00,9.00,10.00,NaN,NaN
concerts,5311.0,50,0.00,5.00,6.820749,7.00,8.00,10.00,NaN,NaN
music,5311.0,50,1.00,7.00,7.834118,8.00,9.00,10.00,NaN,NaN
shopping,5311.0,50,1.00,4.00,5.612691,6.00,8.00,10.00,NaN,NaN
yoga,5311.0,50,0.00,2.00,4.328752,4.00,6.00,10.00,NaN,NaN
interests_correlate,5256.0,105,-0.83,-0.02,0.197053,0.22,0.43,0.91,NaN,NaN
expected_happy_with_sd_people,5297.0,64,1.00,5.00,5.534076,6.00,7.00,10.00,NaN,NaN
expected_num_interested_in_me,1147.0,4214,0.00,2.00,5.636443,4.00,8.00,20.00,NaN,NaN
expected_num_matches,4578.0,783,0.00,2.00,3.181870,3.00,4.00,18.00,NaN,NaN
like,5200.0,161,0.00,5.00,6.141442,6.00,7.00,10.00,NaN,NaN
guess_prob_liked,5163.0,198,0.00,4.00,5.219543,5.00,7.00,10.00,NaN,NaN
met,5107.0,254,0.00,0.00,0.051302,0.00,0.00,8.00,NaN,NaN
decision,5361.0,0,0.00,0.00,0.419884,0.00,1.00,1.00,0.324657,-1.894598
decision_o,5361.0,0,0.00,0.00,0.422123,0.00,1.00,1.00,0.315358,-1.900549
match,5361.0,0,0.00,0.00,0.168998,0.00,0.00,1.00,1.766518,1.120586

In [ ]:
### Qualitative Univariate Analysis